### ISSUE TITLE
Followup popup refinements

### ISSUE THREAD

**Issue by jthrilly** [jthrilly/netCanvas#13]
Followup popups (on multibin and ordbin interfaces) should be refined before release.

Specifically:

- They should disable interaction with other elements and set the background to .blurry
- They should animate in and out suitably

**Comment by jthrilly** [comment]
Pat: can you check if other fixes have solved the issue with the background still being interactive when the followup popup is visible?

**Comment by pfsj** [comment]
You can still interact with the background when the popups are active. This is potentially problematic because if you drag an alter into a bin (e.g., "Not Listed" for sexual orientation options), the popup screen (i.e., "Which other term would you use to describe their sexual orientation?") shows up but if, before closing or entering data in the popup, you drag additional alters into bins that initiate a popup, the subsequent popups for the additional alters is not displayed.
