### ISSUE TITLE
Add Alter's name to sex questions

### ISSUE THREAD

**Issue by glp2** [jthrilly/netCanvas#42]
{label:'CAT: Vaginal sex?', page:'multibin9.html'}
- Is it possible to indicate the alter’s name in the pop up box somewhere: “How many times did you have vaginal sex with [Alter name] in the past 6 months?”
<!script>
        …
        {
        prompt: ‘How many times did you have vaginal sex with
them in the past six months?’,
            variable:’vaginal_sex_freq_t0’,
        }]
        …
    <!/script>

{label:'CAT: Anal sex?', page:'multibin10.html'}
- Is it possible to indicate the alter’s name in the pop up box somewhere: “How many times did you have anal sex with [Alter name] in the past 6 months?”
<!script>
        …
        {
        prompt: ‘How many times did you have anal sex with
them in the past six months?’,
            variable:’anal_sex_freq_t0’,
        }]
        …
    <!/script>

**Comment by jthrilly** [comment]
I've looked into this and it is too complicated to implement in the time we have. Similar to #3 in that we need to improve the way that instances of interfaces are defined. It would be good to have a template syntax for the prompts, so that you could do things like: "How many times did you have sex with {alter} before {today-6months}". For now, I think we have to postpone.
