### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#86]
An error seems to occur when trying to remove ties between nodes. Below are the steps that seem to produce the error every time for me.

Assuming you have reached the “NETEDGE: Social” screen and that you have three nodes: A, B, and C. 
Connect A to B
Connect B to C
Then try to remove the connection between B and A by first clicking on B and then A. 

This gets me the following error titled “Uncaught node.js Error”.

![uncaughtnode](https://cloud.githubusercontent.com/assets/10948594/6697392/3ef478b0-ccbe-11e4-81dc-25c457952edf.png)

**Comment by jthrilly** [comment]
Unusual bug this one. Caused by removing an item from an array as it is being looped over. Of course this changes the length of the array, but the for loop only calculates the length at the start. This means that it will try to access an index that is no longer in the array, which therefore has 'undefined' properties. My solution isn't elegant, but I'm not sure how else to handle it without using array filtering.

Uploading a new build now.

**Comment by jthrilly** [comment]
New release added.
