### ISSUE TITLE
Interviewer ID on first page

### ISSUE THREAD

**Issue by pfsj** [jthrilly/netCanvas#91]
We're looking to enhance our capabilities for data quality control and would like to include an additional entry box on the first page for a 2-digit interviewer ID. This data could potentially be written in the "session" section of the json but let me know if you had other ideas. I assume this would be an adjustment to the RADAR protocol? Let me know if you have any questions.

**Comment by jthrilly** [comment]
Yes, this is something we will do in the protocol file since the intro step
is contained entirely within there.

Are you able to set up a github repository for the RADAR protocol, either
under a personal account or under an organisational account? Once you have
done that, please make me a collaborator and I will take care of uploading
the protocol correctly. If you get stuck, shoot me an email.
